# Generated by Django 4.0.6 on 2022-08-30 00:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen'),
        ),
    ]
