# Generated by Django 4.0.6 on 2022-08-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuario/logouser.png', upload_to='usuario'),
        ),
    ]
