# Generated by Django 4.0.6 on 2022-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(default='noticia/default.png', upload_to='noticia')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
