# Generated by Django 4.0.6 on 2022-08-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_alter_noticia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-fecha',)},
        ),
    ]
