# Generated by Django 4.0.6 on 2022-08-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
